import React from 'react'
import { Button, DatePicker, Form, Input, TimePicker, Select } from "antd";
import moment from "moment";
const {Option} = Select;

export default function TimezonePickerTest() {
    return (
      <div>
        <Select showSearch name="user[time_zone]" id="user_time_zone">
          <Option value="American Samoa2">({moment().subtract(11, 'hours').format('hh:mm a')}) American Samoa</Option>
          <Option value="American Samoa"> ({moment().add(- (11*60 + 0), 'minutes').format('hh:mm a')}) American Samoa</Option>
          <Option value="International Date Line West "> ({moment.utc().add(- (11*60 + 0), 'minutes').format('hh:mm a')}) International Date Line West </Option>
          <Option value="Midway Island">0) Midway Island</Option>
          <Option value="Hawaii"> ({moment.utc().add(- (10*60 + 00), 'minutes').format('hh:mm a')}) Hawaii</Option>
          <Option value="Alaska">(GMT-09:00) Alaska</Option>
          <Option value="Pacific Time (US &amp; Canada)"> (GMT-08:00), 'minutes').format('hh:mm a')}) Pacific Time (US &amp; Canada) </Option>
          <Option value="Tijuana">0) Tijuana</Option>
          <Option value="Arizona">(GMT-07:00) Arizona</Option>
          <Option value="Chihuahua">(GMT-07:00) Chihuahua</Option>
          <Option value="Mazatlan">(GMT-07:00) Mazatlan</Option>
          <Option value="Mountain Time (US &amp; Canada)"> (GMT-07:00) Mountain Time (US &amp; Canada) </Option>
          <Option value="Central America">(GMT-06:00) Central America</Option>
          <Option value="Central Time (US &amp; Canada)"> (GMT-06:00) Central Time (US &amp; Canada) </Option>
          <Option value="Guadalajara">(GMT-06:00) Guadalajara</Option>
          <Option value="Mexico City">(GMT-06:00) Mexico City</Option>
          <Option value="Monterrey">(GMT-06:00) Monterrey</Option>
          <Option value="Saskatchewan">(GMT-06:00) Saskatchewan</Option>
          <Option value="Bogota">(GMT-05:00) Bogota</Option>
          <Option value="Eastern Time (US &amp; Canada)"> (GMT-05:00) Eastern Time (US &amp; Canada) </Option>
          <Option value="Indiana (East)">(GMT-05:00) Indiana (East)</Option>
          <Option value="Lima">(GMT-05:00) Lima</Option>
          <Option value="Quito">(GMT-05:00) Quito</Option>
          <Option value="Atlantic Time (Canada)"> (GMT-04:00) Atlantic Time (Canada) </Option>
          <Option value="Caracas">(GMT-04:00) Caracas</Option>
          <Option value="Georgetown">(GMT-04:00) Georgetown</Option>
          <Option value="La Paz">(GMT-04:00) La Paz</Option>
          <Option value="Santiago">(GMT-04:00) Santiago</Option>
          <Option value="Newfoundland">(GMT-03:30) Newfoundland</Option>
          <Option value="Brasilia">(GMT-03:00) Brasilia</Option>
          <Option value="Buenos Aires">(GMT-03:00) Buenos Aires</Option>
          <Option value="Greenland">(GMT-03:00) Greenland</Option>
          <Option value="Montevideo">(GMT-03:00) Montevideo</Option>
          <Option value="Mid-Atlantic">(GMT-02:00) Mid-Atlantic</Option>
          <Option value="Azores">(GMT-01:00) Azores</Option>
          <Option value="Cape Verde Is.">(GMT-01:00) Cape Verde Is.</Option>
          <Option value="Edinburgh">(GMT+00:00) Edinburgh</Option>
          <Option value="Lisbon">(GMT+00:00) Lisbon</Option>
          <Option value="London">(GMT+00:00) London</Option>
          <Option value="Monrovia">(GMT+00:00) Monrovia</Option>
          <Option value="UTC">(GMT+00:00) UTC</Option>
          <Option value="Amsterdam">(GMT+01:00) Amsterdam</Option>
          <Option value="Belgrade">(GMT+01:00) Belgrade</Option>
          <Option value="Berlin">(GMT+01:00) Berlin</Option>
          <Option value="Bern">(GMT+01:00) Bern</Option>
          <Option value="Bratislava">(GMT+01:00) Bratislava</Option>
          <Option value="Brussels">(GMT+01:00) Brussels</Option>
          <Option value="Budapest">(GMT+01:00) Budapest</Option>
          <Option value="Casablanca">(GMT+01:00) Casablanca</Option>
          <Option value="Copenhagen">(GMT+01:00) Copenhagen</Option>
          <Option value="Dublin">(GMT+01:00) Dublin</Option>
          <Option value="Europe/Berlin">(GMT+01:00) Europe/Berlin</Option>
          <Option value="Ljubljana">(GMT+01:00) Ljubljana</Option>
          <Option value="Madrid"> (GMT+01:00) Madrid </Option>
          <Option value="Paris">(GMT+01:00) Paris</Option>
          <Option value="Prague">(GMT+01:00) Prague</Option>
          <Option value="Rome">(GMT+01:00) Rome</Option>
          <Option value="Sarajevo">(GMT+01:00) Sarajevo</Option>
          <Option value="Skopje">(GMT+01:00) Skopje</Option>
          <Option value="Stockholm">(GMT+01:00) Stockholm</Option>
          <Option value="Vienna">(GMT+01:00) Vienna</Option>
          <Option value="Warsaw">(GMT+01:00) Warsaw</Option>
          <Option value="West Central Africa"> (GMT+01:00) West Central Africa </Option>
          <Option value="Zagreb">(GMT+01:00) Zagreb</Option>
          <Option value="Zurich">(GMT+01:00) Zurich</Option>
          <Option value="Athens">(GMT+02:00) Athens</Option>
          <Option value="Bucharest">(GMT+02:00) Bucharest</Option>
          <Option value="Cairo">(GMT+02:00) Cairo</Option>
          <Option value="Harare">(GMT+02:00) Harare</Option>
          <Option value="Helsinki">(GMT+02:00) Helsinki</Option>
          <Option value="Jerusalem">(GMT+02:00) Jerusalem</Option>
          <Option value="Kaliningrad">(GMT+02:00) Kaliningrad</Option>
          <Option value="Kyiv">(GMT+02:00) Kyiv</Option>
          <Option value="Pretoria">(GMT+02:00) Pretoria</Option>
          <Option value="Riga">(GMT+02:00) Riga</Option>
          <Option value="Sofia">(GMT+02:00) Sofia</Option>
          <Option value="Tallinn">(GMT+02:00) Tallinn</Option>
          <Option value="Vilnius">(GMT+02:00) Vilnius</Option>
          <Option value="Baghdad">(GMT+03:00) Baghdad</Option>
          <Option value="Istanbul">(GMT+03:00) Istanbul</Option>
          <Option value="Kuwait">(GMT+03:00) Kuwait</Option>
          <Option value="Minsk">(GMT+03:00) Minsk</Option>
          <Option value="Moscow">(GMT+03:00) Moscow</Option>
          <Option value="Nairobi">(GMT+03:00) Nairobi</Option>
          <Option value="Riyadh">(GMT+03:00) Riyadh</Option>
          <Option value="St. Petersburg">(GMT+03:00) St. Petersburg</Option>
          <Option value="Tehran">(GMT+03:30) Tehran</Option>
          <Option value="Abu Dhabi">(GMT+04:00) Abu Dhabi</Option>
          <Option value="Baku">(GMT+04:00) Baku</Option>
          <Option value="Muscat">(GMT+04:00) Muscat</Option>
          <Option value="Samara">(GMT+04:00) Samara</Option>
          <Option value="Tbilisi">(GMT+04:00) Tbilisi</Option>
          <Option value="Volgograd">(GMT+04:00) Volgograd</Option>
          <Option value="Yerevan">(GMT+04:00) Yerevan</Option>
          <Option value="Kabul">(GMT+04:30) Kabul</Option>
          <Option value="Ekaterinburg">(GMT+05:00) Ekaterinburg</Option>
          <Option value="Islamabad">(GMT+05:00) Islamabad</Option>
          <Option value="Karachi">(GMT+05:00) Karachi</Option>
          <Option value="Tashkent">(GMT+05:00) Tashkent</Option>
          <Option value="Chennai">(GMT+05:30) Chennai</Option>
          <Option value="Kolkata">(GMT+05:30) Kolkata</Option>
          <Option value="Mumbai">(GMT+05:30) Mumbai</Option>
          <Option value="New Delhi">(GMT+05:30) New Delhi</Option>
          <Option value="Sri Jayawardenepura"> (GMT+05:30) Sri Jayawardenepura </Option>
          <Option value="Kathmandu">(GMT+05:45) Kathmandu</Option>
          <Option value="Almaty">(GMT+06:00) Almaty</Option>
          <Option value="Astana">(GMT+06:00) Astana</Option>
          <Option value="Dhaka">(GMT+06:00) Dhaka</Option>
          <Option value="Urumqi">(GMT+06:00) Urumqi</Option>
          <Option value="Rangoon">(GMT+06:30) Rangoon</Option>
          <Option value="Bangkok">(GMT+07:00) Bangkok</Option>
          <Option value="Hanoi">(GMT+07:00) Hanoi</Option>
          <Option value="Jakarta">(GMT+07:00) Jakarta</Option>
          <Option value="Krasnoyarsk">(GMT+07:00) Krasnoyarsk</Option>
          <Option value="Novosibirsk">(GMT+07:00) Novosibirsk</Option>
          <Option value="Beijing">(GMT+08:00) Beijing</Option>
          <Option value="Chongqing">(GMT+08:00) Chongqing</Option>
          <Option value="Hong Kong">(GMT+08:00) Hong Kong</Option>
          <Option value="Irkutsk">(GMT+08:00) Irkutsk</Option>
          <Option value="Kuala Lumpur">(GMT+08:00) Kuala Lumpur</Option>
          <Option value="Perth">(GMT+08:00) Perth</Option>
          <Option value="Singapore">(GMT+08:00) Singapore</Option>
          <Option value="Taipei">(GMT+08:00) Taipei</Option>
          <Option value="Ulaanbaatar">(GMT+08:00) Ulaanbaatar</Option>
          <Option value="Osaka">(GMT+09:00) Osaka</Option>
          <Option value="Sapporo">(GMT+09:00) Sapporo</Option>
          <Option value="Seoul">(GMT+09:00) Seoul</Option>
          <Option value="Tokyo">(GMT+09:00) Tokyo</Option>
          <Option value="Yakutsk">(GMT+09:00) Yakutsk</Option>
          <Option value="Adelaide">(GMT+09:30) Adelaide</Option>
          <Option value="Darwin">(GMT+09:30) Darwin</Option>
          <Option value="Brisbane">(GMT+10:00) Brisbane</Option>
          <Option value="Canberra">(GMT+10:00) Canberra</Option>
          <Option value="Guam">(GMT+10:00) Guam</Option>
          <Option value="Hobart">(GMT+10:00) Hobart</Option>
          <Option value="Melbourne">(GMT+10:00) Melbourne</Option>
          <Option value="Port Moresby">(GMT+10:00) Port Moresby</Option>
          <Option value="Sydney">(GMT+10:00) Sydney</Option>
          <Option value="Vladivostok">(GMT+10:00) Vladivostok</Option>
          <Option value="Magadan">(GMT+11:00) Magadan</Option>
          <Option value="New Caledonia">(GMT+11:00) New Caledonia</Option>
          <Option value="Solomon Is.">(GMT+11:00) Solomon Is.</Option>
          <Option value="Srednekolymsk">(GMT+11:00) Srednekolymsk</Option>
          <Option value="Auckland">(GMT+12:00) Auckland</Option>
          <Option value="Fiji">(GMT+12:00) Fiji</Option>
          <Option value="Kamchatka">(GMT+12:00) Kamchatka</Option>
          <Option value="Marshall Is.">(GMT+12:00) Marshall Is.</Option>
          <Option value="Wellington">(GMT+12:00) Wellington</Option>
          <Option value="Chatham Is.">(GMT+12:45) Chatham Is.</Option>
          <Option value="Nuku'alofa">(GMT+13:00) Nuku'alofa</Option>
          <Option value="Samoa">(GMT+13:00) Samoa</Option>
          <Option value="Tokelau Is.">(GMT+13:00) Tokelau Is.</Option>
        </Select>
      </div>
    );
}
